In [11]:
import pandas as pd

In [12]:
# 1.- Cargar el archivo a un Data Frame llamado “cereal” 
cereal = pd.read_csv('./files/cereals.csv')

In [13]:
cereal

,Name,Manuf,Type,Calories,Protein,Fat,Sodium,Fiber,Carbo,Sugars,...,Weight,Cups,Rating,Cold,Nabisco,Quaker,Kelloggs,GeneralMills,Ralston,AHFP
0,100%_Bran,N,C,70,4,1,130,10.0,5.0,6.0,...,1.0,0.33,68.402973,1,1,0,0,0,0,0
1,100%_Natural_Bran,Q,C,120,3,5,15,2.0,8.0,8.0,...,1.0,1.00,33.983679,1,0,1,0,0,0,0
2,All-Bran,K,C,70,4,1,260,9.0,7.0,5.0,...,1.0,0.33,59.425505,1,0,0,1,0,0,0
3,All-Bran_with_Extra_Fiber,K,C,50,4,0,140,14.0,8.0,0.0,...,1.0,0.50,93.704912,1,0,0,1,0,0,0
4,Almond_Delight,R,C,110,2,2,200,1.0,14.0,8.0,...,1.0,0.75,34.384843,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72,Triples,G,C,110,2,1,250,0.0,21.0,3.0,...,1.0,0.75,39.106174,1,0,0,0,1,0,0
73,Trix,G,C,110,1,1,140,0.0,13.0,12.0,...,1.0,1.00,27.753301,1,0,0,0,1,0,0
74,Wheat_Chex,R,C,100,3,1,230,3.0,17.0,3.0,...,1.0,0.67,49.787445,1,0,0,0,0,1,0
75,Wheaties,G,C,100,3,1,200,3.0,17.0,3.0,...,1.0,1.00,51.592193,1,0,0,0,1,0,0
76,Wheaties_Honey_Gold,G,C,110,2,1,200,1.0,16.0,8.0,...,1.0,0.75,36.187559,1,0,0,0,1,0,0

In [14]:
# 1.- Crear un subconjunto de 20 registros completos (independiente llamado “scereal” con los atributos (name, Manuf, Type, Calories, Protein, Sodium, Potass, Vitamins).
scereal = cereal[['Name', 'Manuf', 'Type', 'Calories', 'Protein', 'Sodium', 'Potass', 'Vitamins']].tail(20)

In [15]:
# 2.- Calcular en “scereal” la raíz cuadrada, media, desviación estandar de 'Calories' 
import numpy as np

scereal.agg({'Calories':['median', 'std']})
np.sqrt(scereal[['Calories']].apply(sum))

Calories    45.607017
dtype: float64

In [16]:
# 2.- Calcular en “scereal” la raíz cuadrada, media, desviación estandar de 'Sodium' 
scereal.agg({'Sodium':['median', 'std']})
np.sqrt(scereal[['Sodium']].apply(sum))

Sodium    52.962251
dtype: float64

In [17]:
# 3.- Sustituir los valores “0” por la media del atributo “Sodium” en “cereal”.
cereal['Sodium'] = cereal['Sodium'].replace(0, cereal['Sodium'].mean())

In [18]:
# 4.- Eliminar los valores “NA” (nulos) en “cereal” y asignarlos a una variable llamada “sncereal”.
sncereal = cereal.dropna()

In [19]:
# 6.- Filtrar "cereal", los atributos (Manuf = K) y (Potass >= 150)
cereal[(cereal['Manuf'] == 'K ') & (cereal['Potass']>=150)]

,Name,Manuf,Type,Calories,Protein,Fat,Sodium,Fiber,Carbo,Sugars,...,Weight,Cups,Rating,Cold,Nabisco,Quaker,Kelloggs,GeneralMills,Ralston,AHFP
2,All-Bran,K,C,70,4,1,260.0,9.0,7.0,5.0,...,1.00,0.33,59.425505,1,0,0,1,0,0,0
3,All-Bran_with_Extra_Fiber,K,C,50,4,0,140.0,14.0,8.0,0.0,...,1.00,0.50,93.704912,1,0,0,1,0,0,0
19,Cracklin'_Oat_Bran,K,C,110,3,3,140.0,4.0,10.0,7.0,...,1.00,0.50,40.448772,1,0,0,1,0,0,0
28,Fruitful_Bran,K,C,120,3,0,240.0,5.0,14.0,12.0,...,1.33,0.67,41.015492,1,0,0,1,0,0,0
46,Mueslix_Crispy_Blend,K,C,160,3,2,150.0,3.0,17.0,13.0,...,1.50,0.67,30.313351,1,0,0,1,0,0,0
58,Raisin_Bran,K,C,120,3,1,210.0,5.0,14.0,12.0,...,1.33,0.75,39.259197,1,0,0,1,0,0,0

In [20]:
# 7.- Filtrar "scereal" por grupos de acuerdo a los atributos (name,Type) y sumarizar el campo ("Calories"), ordenarlo de mayor a menor (descendente)
scereal.groupby(['Name', 'Type'])[['Calories']].apply(sum).sort_values('Calories', ascending = False)

                                 Calories
Name                       Type
Total_Raisin_Bran          C          140
Raisin_Bran                C          120
Special_K                  C          110
Smacks                     C          110
Trix                       C          110
Triples                    C          110
Total_Corn_Flakes          C          110
Wheaties_Honey_Gold        C          110
Rice_Krispies              C          110
Rice_Chex                  C          110
Total_Whole_Grain          C          100
Raisin_Nut_Bran            C          100
Wheat_Chex                 C          100
Wheaties                   C          100
Quaker_Oatmeal             H          100
Shredded_Wheat_spoon_size  C           90
Shredded_Wheat_'n'Bran     C           90
Strawberry_Fruit_Wheats    C           90
Raisin_Squares             C           90
Shredded_Wheat             C           80

In [21]:
# 8.- Tomando como base "scereal", encontrar las funciones ("media", "desviación estandar", "raíz cuadrada") que se aplique a todos los campos cuantitativos (es decir, Calories, Protein, Sodium, Potass, Vitamins). Encontrar una forma elegante de resumirlo (existen varias alternativas).
numerics = ['int16', 'int32', 'int64', 'float16', 'float32', 'float64']
scereal.select_dtypes(include=numerics).agg(['min', 'max', 'mean', 'median', 'std'])

          Calories   Protein      Sodium    Potass    Vitamins
min      80.000000  1.000000    0.000000   25.0000    0.000000
max     140.000000  6.000000  290.000000  240.0000  100.000000
mean    104.000000  2.650000  140.250000   97.5000   31.250000
median  105.000000  2.500000  195.000000  102.5000   25.000000
std      13.138934  1.182103  102.885667   60.0548   31.282877

In [22]:
# 9.- Utilizando el archivo "cereals2.csv", combinar el conjunto de datos "cereals.csv" con "cereals2.csv" tomando como base el atrinuto "name" y nombrarlo "supercereal"
supercereal = pd.merge(cereal, pd.read_csv('./files/cereals2.csv'), on="Name") 
supercereal

,Name,Manuf_x,Type_x,Calories_x,Protein_x,Fat_x,Sodium_x,Fiber_x,Carbo_x,Sugars_x,...,Weight_y,Cups_y,Rating_y,Cold_y,Nabisco_y,Quaker_y,Kelloggs_y,GeneralMills_y,Ralston_y,AHFP_y
0,100%_Natural_Bran,Q,C,120,3,5,15.000000,2.0,8.0,8.0,...,1.00,1.00,33.983679,1,0,1,0,0,0,0
1,Almond_Delight,R,C,110,2,2,200.000000,1.0,14.0,8.0,...,1.00,0.75,34.384843,1,0,0,0,0,1,0
2,Bran_Chex,R,C,90,2,1,200.000000,4.0,15.0,6.0,...,1.00,0.67,49.120253,1,0,0,0,0,1,0
3,Bran_Flakes,P,C,90,3,0,210.000000,5.0,13.0,5.0,...,1.00,0.67,53.313813,1,0,0,0,0,0,0
4,Cap'n'Crunch,Q,C,120,1,2,220.000000,0.0,12.0,12.0,...,1.00,0.75,18.042851,1,0,1,0,0,0,0
5,Corn_Chex,R,C,110,2,0,280.000000,0.0,22.0,3.0,...,1.00,1.00,41.445019,1,0,0,0,0,1,0
6,Double_Chex,R,C,100,2,0,190.000000,1.0,18.0,5.0,...,1.00,0.75,44.330856,1,0,0,0,0,1,0
7,"Fruit_&_Fibre_Dates,_Walnuts,_and_Oats",P,C,120,3,2,160.000000,5.0,12.0,10.0,...,1.25,0.67,40.917047,1,0,0,0,0,0,0
8,Fruity_Pebbles,P,C,110,1,1,135.000000,0.0,13.0,12.0,...,1.00,0.75,28.025765,1,0,0,0,0,0,0
9,Golden_Crisp,P,C,100,2,0,45.000000,0.0,11.0,15.0,...,1.00,0.88,35.252444,1,0,0,0,0,0,0
10,Grape_Nuts_Flakes,P,C,100,3,1,140.000000,3.0,15.0,5.0,...,1.00,0.88,52.076897,1,0,0,0,0,0,0
11,Grape-Nuts,P,C,110,3,0,170.000000,3.0,17.0,3.0,...,1.00,0.25,53.371007,1,0,0,0,0,0,0
12,Great_Grains_Pecan,P,C,120,3,3,75.000000,3.0,13.0,4.0,...,1.00,0.33,45.811716,1,0,0,0,0,0,0
13,Honey_Graham_Ohs,Q,C,120,1,2,220.000000,1.0,12.0,11.0,...,1.00,1.00,21.871292,1,0,1,0,0,0,0
14,Honey-comb,P,C,110,1,0,180.000000,0.0,14.0,11.0,...,1.00,1.33,28.742414,1,0,0,0,0,0,0
15,Life,Q,C,100,4,2,150.000000,2.0,12.0,6.0,...,1.00,0.67,45.328074,1,0,1,0,0,0,0
16,"Muesli_Raisins,_Dates,_&_Almonds",R,C,150,4,3,95.000000,3.0,16.0,11.0,...,1.00,1.00,37.136863,1,0,0,0,0,1,0
17,"Muesli_Raisins,_Peaches,_&_Pecans",R,C,150,4,3,150.000000,3.0,16.0,11.0,...,1.00,1.00,34.139765,1,0,0,0,0,1,0
18,Post_Nat._Raisin_Bran,P,C,120,3,1,200.000000,6.0,11.0,14.0,...,1.33,0.67,37.840594,1,0,0,0,0,0,0
19,Puffed_Rice,Q,C,50,1,0,159.675325,0.0,13.0,0.0,...,0.50,1.00,60.756112,1,0,1,0,0,0,0
20,Puffed_Wheat,Q,C,50,2,0,159.675325,1.0,10.0,0.0,...,0.50,1.00,63.005645,1,0,1,0,0,0,0
21,Quaker_Oat_Squares,Q,C,100,4,1,135.000000,2.0,14.0,6.0,...,1.00,0.50,49.511874,1,0,1,0,0,0,0
22,Quaker_Oatmeal,Q,H,100,5,2,159.675325,2.7,NaN,NaN,...,1.00,0.67,50.828392,0,0,1,0,0,0,0
23,Rice_Chex,R,C,110,1,0,240.000000,0.0,23.0,2.0,...,1.00,1.13,41.998933,1,0,0,0,0,1,0
24,Wheat_Chex,R,C,100,3,1,230.000000,3.0,17.0,3.0,...,1.00,0.67,49.787445,1,0,0,0,0,1,0

In [23]:
# 10.- Utilizar el Data Frame "supercereal" y aplicar las funciones descritas en el punto 8.
supercereal.select_dtypes(include=numerics).agg(['min', 'max', 'mean', 'median', 'std'])

,Calories_x,Protein_x,Fat_x,Sodium_x,Fiber_x,Carbo_x,Sugars_x,Potass_x,Vitamins_x,Shelf_x,...,Weight_y,Cups_y,Rating_y,Cold_y,Nabisco_y,Quaker_y,Kelloggs_y,GeneralMills_y,Ralston_y,AHFP_y
min,50.000000,1.000000,0.00000,15.000000,0.000000,8.000000,0.000000,15.000000,0.000000,1.000000,...,0.500000,0.25000,18.042851,0.00,0.0,0.000000,0.0,0.0,0.000000,0.0
max,150.000000,5.000000,5.00000,280.000000,6.000000,23.000000,15.000000,260.000000,25.000000,3.000000,...,1.330000,1.33000,63.005645,1.00,0.0,1.000000,0.0,0.0,1.000000,0.0
mean,106.400000,2.520000,1.28000,164.761039,2.028000,14.208333,7.125000,97.291667,21.000000,2.280000,...,0.983200,0.79960,42.040944,0.96,0.0,0.320000,0.0,0.0,0.320000,0.0
median,110.000000,3.000000,1.00000,160.000000,2.000000,13.500000,6.000000,92.500000,25.000000,3.000000,...,1.000000,0.75000,41.998933,1.00,0.0,0.000000,0.0,0.0,0.000000,0.0
std,22.524061,1.159023,1.30767,60.753473,1.785012,3.476370,4.337025,65.041444,9.354143,0.890693,...,0.166376,0.24361,11.274476,0.20,0.0,0.476095,0.0,0.0,0.476095,0.0